(* infotheo: information theory and error-correcting codes in Rocq            *)
(* Copyright (C) 2025 infotheo authors, license: LGPL-2.1-or-later            *)
(******************************************************************************)
(* Z_7 wr S_2 wreath spectral convergence: a SecurityAsymptotic for the plug  *)
(*                                                                            *)
(* Brings the wreath plug up to the S_5 standard (see s5_mixing.v): a          *)
(* SecurityAsymptotic with additive floor sa_eps_inf = 0 and geometric decay   *)
(*   var_dist (sigma s) uniform <= sqrt(14) * (1 - gap)^L.                     *)
(*                                                                            *)
(* THE OBSTRUCTION the wreath does not share with S_5.                         *)
(*   The S_5 engine symm_ds_TV_bound derives symmetry of the Schreier          *)
(*   transition from per-generator INVOLUTIVITY (g^2 = 1). The wreath cuts      *)
(*   cut1, cut2 are 7-CYCLES, not involutions, so the 3-generator transition    *)
(*   [cut1; cut2; wswap] is NOT symmetric and that engine does not apply.       *)
(*   (Z_7 has odd order, so the base group cannot be generated by involutions   *)
(*   at all.)                                                                  *)
(*                                                                            *)
(* THE FIX (group-preserving).                                                 *)
(*   Adjoin the inverses: wreath_sym_gens = [cut1; cut1^-1; cut2; cut2^-1;      *)
(*   wswap]. The generating MULTISET is now closed under inverse, so the        *)
(*   Schreier transition is symmetric (wreath_schreier_symm) WITHOUT each       *)
(*   generator being an involution. Adjoining inverses does not change the      *)
(*   generated group (wreath_sym_same_group), so the plug is still Z_7 wr S_2.  *)
(*   The walk is connected on all 14 positions (cut1 mixes pile 1, wswap        *)
(*   crosses to pile 2, cut2 mixes pile 2), hence irreducible: the stationary   *)
(*   law is uniform and sa_eps_inf = 0.                                         *)
(*                                                                            *)
(* The sole imported assumption is wreath_rayleigh_Qsq_R, the Rayleigh bound    *)
(* on Q^2 at alpha^2 over mean-zero vectors, mirroring s5_rayleigh_Qsq_R; it    *)
(* is certified externally by wreath_spectral_certificate.py in this directory. *)
(* Every other step is a structural Rocq proof.                                 *)
(******************************************************************************)

From HB Require Import structures.
From mathcomp Require Import ssreflect ssrbool ssrfun eqtype ssrnat seq.
From mathcomp Require Import div fintype tuple finfun finset fingroup perm.
From mathcomp Require Import bigop order ssrnum ssralg matrix.
From mathcomp Require Import boolp reals.
From infotheo Require Import realType_ext fdist proba variation_dist.
From pgg_smc Require Import pgg_interface pgg_weval_inj pgg_raag.
From pgg_smc Require Import pgg_collusion_bound pgg_schreier pgg_mixing.
From pgg_smc Require Import pgg_wreath.
From pgg_reconstruct Require Import algebraic_rigidity.

Set Implicit Arguments.
Unset Strict Implicit.
Import Prenex Implicits.

Local Open Scope ring_scope.
Local Open Scope fdist_scope.

Import GRing.Theory Num.Theory.

(******************************************************************************)
(*  Section 1. The symmetric (inverse-closed) generating multiset.            *)
(******************************************************************************)

(** wreath_sym_gens — the inverse-closed five-generator multiset of Z_7 wr S_2.
    Kind: instance.
    Why: cut1, cut2 are 7-cycles, so the bare [cut1; cut2; wswap] Schreier
    transition is not symmetric. Adjoining cut1^-1, cut2^-1 (wswap is its own
    inverse) closes the multiset under inverse, making the transition symmetric
    without changing the generated group.
    Used by: M_wreath_sym, wreath_schreier_symm, wreath_rayleigh_Qsq_R. *)
Definition wreath_sym_gens : 5.-tuple {perm 'I_14} :=
  [tuple cut1; (cut1^-1)%g; cut2; (cut2^-1)%g; wswap].

(** M_wreath_sym — the wreath monodromy over the inverse-closed generators.
    Kind: instance.
    Why: same group as M_wreath (Z_7 wr S_2 on 14 cards), but with the
    symmetric generating multiset, so its Schreier walk admits the spectral
    mixing argument. Carries the SecurityAsymptotic below. *)
Definition M_wreath_sym : MonodromyReprWithGeneratorType :=
  @Gen_PGGTypes 4 12 wreath_sym_gens.

(** wreath_sym_same_group — adjoining inverses preserves the generated group.
    Kind: helper.
    Why: certifies that the symmetric monodromy M_wreath_sym is still the
    wreath Z_7 wr S_2, so the plug's structural anonymity (|G| = 98,
    non-abelian) is unchanged by the symmetrisation.
    Used by: the plug rewiring; not load-bearing for the mixing bound. *)
Lemma wreath_sym_same_group : pgg_G M_wreath_sym = pgg_G M_wreath.
Proof.
rewrite /M_wreath_sym /M_wreath /=.
apply/val_inj => /=; apply/eqP; rewrite eqEsubset; apply/andP; split.
- (* <<S5>> <= <<S3>>: every symmetric generator lies in <<S3>>; the inverses
     cut1^-1, cut2^-1 via groupV. *)
  rewrite gen_subG; apply/subsetP => x /imsetP [i _ ->].
  have memg : forall j : 'I_3,
      tnth wreath_gens j \in <<[set tnth wreath_gens i0 | i0 : 'I_3]>>%G.
    by move=> j; apply: mem_gen; apply/imsetP; exists j.
  case: i => -[|[|[|[|[|i']]]]] Hi //; rewrite (tnth_nth 1%g) /=.
  + by have := memg (@Ordinal 3 0 isT); rewrite (tnth_nth 1%g) /=.
  + rewrite groupV.
    by have := memg (@Ordinal 3 0 isT); rewrite (tnth_nth 1%g) /=.
  + by have := memg (@Ordinal 3 1 isT); rewrite (tnth_nth 1%g) /=.
  + rewrite groupV.
    by have := memg (@Ordinal 3 1 isT); rewrite (tnth_nth 1%g) /=.
  + by have := memg (@Ordinal 3 2 isT); rewrite (tnth_nth 1%g) /=.
- (* <<S3>> <= <<S5>>: S3 is a subset of S5, then genS. *)
  apply: genS; apply/subsetP => y /imsetP [j _ ->].
  case: j => -[|[|[|j']]] Hj //; rewrite (tnth_nth 1%g) /=.
  + by apply/imsetP; exists (@Ordinal 5 0 isT); rewrite ?(tnth_nth 1%g) /=.
  + by apply/imsetP; exists (@Ordinal 5 2 isT); rewrite ?(tnth_nth 1%g) /=.
  + by apply/imsetP; exists (@Ordinal 5 4 isT); rewrite ?(tnth_nth 1%g) /=.
Qed.

(******************************************************************************)
(*  Section 2. Inverse-closure of the generator multiset.                     *)
(******************************************************************************)

(** wreath_inv_pairing — the index involution pairing each generator with its
    inverse: 0<->1 (cut1<->cut1^-1), 2<->3 (cut2<->cut2^-1), 4 fixed (wswap).
    Kind: helper.
    Why: the bijection on 'I_5 that witnesses inverse-closure of the multiset.
    Used by: wreath_gens_inv_closed, wreath_schreier_symm. *)
Definition wreath_inv_pairing : 'I_5 -> 'I_5 :=
  fun k => tperm (@Ordinal 5 0 isT) (@Ordinal 5 1 isT)
                 (tperm (@Ordinal 5 2 isT) (@Ordinal 5 3 isT) k).

(** wreath_inv_pairing_inv — the index pairing is an involution.
    Kind: helper.
    Why: the pairing is the product of two disjoint transpositions, so it
    equals its own inverse; this makes it a bijection on 'I_5 used to reindex
    the generator count in wreath_schreier_symm.
    Used by: wreath_schreier_symm. *)
Lemma wreath_inv_pairing_inv : involutive wreath_inv_pairing.
Proof.
move=> k; rewrite /wreath_inv_pairing.
by case: k => -[|[|[|[|[|k']]]]] Hk //; apply/val_inj; rewrite !permE /=.
Qed.

(** wreath_gens_inv_closed — every generator's mirror under the pairing is its
    inverse.
    Kind: helper.
    Why: the algebraic content of inverse-closure; drives the symmetry of the
    Schreier transition. Mechanical: compute each of the five indices.
    Used by: wreath_schreier_symm. *)
Lemma wreath_gens_inv_closed (k : 'I_5) :
  tnth wreath_sym_gens (wreath_inv_pairing k)
    = ((tnth wreath_sym_gens k)^-1)%g.
Proof.
case: k => -[|[|[|[|[|k']]]]] Hk //.
all: rewrite /wreath_inv_pairing !permE /=.
all: rewrite !(tnth_nth 1%g) /=.
all: rewrite ?invgK //.
(* index 4: wswap is its own inverse, since wswap^2 = 1 *)
suff Hinv : (wswap * wswap)%g = 1%g.
  by rewrite -(mulg1_eq Hinv) invgK; exact: mulg1_eq Hinv.
apply/permP => x; rewrite perm1 permM.
case: x => -[|[|[|[|[|[|[|[|[|[|[|[|[|[|]]]]]]]]]]]]]] Hx //;
  apply/val_inj; rewrite /wswap !permM !permE; by [].
Qed.

(******************************************************************************)
(*  Section 3. Symmetry of the Schreier transition from inverse-closure.      *)
(******************************************************************************)

(** wreath_schreier_symm — the Schreier transition of the inverse-closed
    multiset is symmetric.
    Kind: main.
    Why: generalises schreier_transition_symm from per-generator involutivity
    to multiset inverse-closure: #{k : g_k i = j} = #{k : g_k j = i} via the
    pairing wreath_inv_pairing. The single structural fact the wreath needs
    that S_5 got for free from involutive transpositions.
    Used by: wreath_spectral_convergence_proved. *)
Lemma wreath_schreier_symm (R : realType) :
  (schreier_transition R wreath_sym_gens)^T
    = schreier_transition R wreath_sym_gens.
Proof.
apply/matrixP => i j; rewrite !mxE.
congr (_%:R / _); rewrite /schreier_gen_count.
(* g_(pairing k) = g_k^-1, hence g_(pairing k) i = j <-> g_k j = i *)
have Heq : forall k,
    (tnth wreath_sym_gens (wreath_inv_pairing k) i == j)
      = (tnth wreath_sym_gens k j == i).
  move=> k; rewrite wreath_gens_inv_closed.
  apply/eqP/eqP => H.
    by rewrite -H permKV.
  by rewrite -H permK.
transitivity
  (#|[set k | tnth wreath_sym_gens (wreath_inv_pairing k) i == j]|).
  by apply: eq_card => k; rewrite !inE Heq.
(* reindex by the involution wreath_inv_pairing, a bijection on 'I_5 *)
rewrite -(card_imset _ (can_inj wreath_inv_pairing_inv)).
apply: eq_card => k; rewrite !inE.
apply/imsetP/idP.
  by move=> [x]; rewrite inE => Hx ->.
move=> Hk; exists (wreath_inv_pairing k);
  rewrite ?inE ?wreath_inv_pairing_inv //.
Qed.

(******************************************************************************)
(*  Section 4. The mixing coefficient alpha and the imported Rayleigh bound.   *)
(******************************************************************************)

(* alpha is a rational upper bound on the second-largest eigenvalue modulus of
   the symmetric Schreier walk on the 14 cards, supplied by
   wreath_spectral_certificate.py in this directory. Analytically the second
   eigenvalue is 3/5 + (2/5) cos(2 pi / 7) ~ 0.84940, and 17/20 = 0.85 bounds it
   (cos(2 pi / 7) < 5/8). It is a rational in [0, 1); the [0,1) bounds below are
   proved, and the certificate attests that alpha^2 * I - Q^2 is PSD on the
   mean-zero hyperplane (all 13 LDL^T pivots strictly positive), i.e. the
   Rayleigh bound wreath_rayleigh_Qsq_R. The wreath gap 1 - alpha = 3/20 is
   wider than the S_5 gap 19/200: the wreath mixes faster. *)
Definition wreath_alpha_R (R : realType) : R := 17%:R / 20%:R.

(** wreath_alpha_R_ge0 — the wreath mixing coefficient is non-negative.
    Kind: helper. Why: locates alpha in [0,1]. Used by: wreath_gap_R_le1. *)
Lemma wreath_alpha_R_ge0 (R : realType) : 0 <= wreath_alpha_R R.
Proof. rewrite /wreath_alpha_R; apply divr_ge0; by rewrite ler0n. Qed.

(** wreath_alpha_R_le1 — the wreath mixing coefficient is at most one.
    Kind: helper. Why: with ge0, locates alpha in [0,1].
    Used by: wreath_gap_R_le1. *)
Lemma wreath_alpha_R_le1 (R : realType) : wreath_alpha_R R <= 1.
Proof.
rewrite /wreath_alpha_R ler_pdivrMr ?mul1r; last by rewrite ltr0n.
by rewrite ler_nat.
Qed.

(** wreath_alpha_R_lt1 — the wreath mixing coefficient is strictly below one.
    Kind: helper. Why: strict bound makes the spectral gap positive.
    Used by: wreath_gap_R_pos. *)
Lemma wreath_alpha_R_lt1 (R : realType) : wreath_alpha_R R < 1.
Proof.
rewrite /wreath_alpha_R ltr_pdivrMr ?mul1r; last by rewrite ltr0n.
by rewrite ltr_nat.
Qed.

(** AXIOM STATUS: certified externally by wreath_spectral_certificate.py in
    this directory (the Z_7 wr S_2 analogue of s5_spectral_certificate.py).
    Only the Rayleigh conclusion enters this development, exactly as for
    s5_rayleigh_Qsq_R. *)
Axiom wreath_rayleigh_Qsq_R :
  forall (R : realType) (v : 'cV[R]_14),
  \sum_i v i ord0 = 0 ->
  (v^T
    *m (schreier_transition R wreath_sym_gens
        *m schreier_transition R wreath_sym_gens)
    *m v) ord0 ord0
  <= (wreath_alpha_R R) ^+ 2 * cV_inner v v.

(******************************************************************************)
(*  Section 5. The variation-distance convergence bound.                      *)
(******************************************************************************)

(** wreath_schreier_col_sum — column sums of the symmetric Schreier transition
    equal 1.
    Kind: helper.
    Why: the row sums are 1 generically (stochastic); the column sums follow
    from symmetry (wreath_schreier_symm), giving double stochasticity, which is
    the hypothesis symm_ds_TV_bound_cV needs. Mirrors
    schreier_transition_doubly_stochastic_col, but draws symmetry from
    multiset inverse-closure rather than per-generator involutivity.
    Used by: wreath_spectral_convergence_proved. *)
Lemma wreath_schreier_col_sum (R : realType) (j : 'I_14) :
  \sum_i schreier_transition R wreath_sym_gens i j = 1.
Proof.
have Hsym := wreath_schreier_symm R.
transitivity (\sum_i schreier_transition R wreath_sym_gens j i).
  apply: eq_bigr => i _.
  have /matrixP /(_ j i) := Hsym.
  by rewrite mxE.
exact: schreier_transition_stochastic.
Qed.

(** wreath_schreier_endpoint_eq — the wreath endpoint pushforward equals the
    matrix-power column entry.
    Kind: helper.
    Why: the bridge from the probabilistic endpoint law fdistmap(sigma s) to
    (Q^L *m e_s), required to feed the column-vector TV engine. Mirrors
    schreier_endpoint_eq_Q_power, using wreath_schreier_symm for the Q^L
    transpose-symmetry and the generic schreier_walk_eq_endpoint.
    Used by: wreath_spectral_convergence_proved. *)
Lemma wreath_schreier_endpoint_eq (R : realType) (L : nat) (s a : 'I_14) :
  fdistmap (fun sigma : {perm 'I_14} => sigma s)
           (rho_from_words L wreath_sym_gens) a
  = ((schreier_transition R wreath_sym_gens) ^+ L
       *m \col_i (i == s)%:R) a ord0.
Proof.
have Hsym := wreath_schreier_symm R.
have HQLsymm :
  ((schreier_transition R wreath_sym_gens) ^+ L)^T
    = (schreier_transition R wreath_sym_gens) ^+ L.
  elim: L => [|L' IH].
    by rewrite expr0 trmx1.
  by rewrite exprS trmx_mul IH -exprS exprSr Hsym.
have entry_eq : forall i j,
    ((schreier_transition R wreath_sym_gens) ^+ L) i j
      = ((schreier_transition R wreath_sym_gens) ^+ L) j i.
  move=> i j.
  have /matrixP /(_ j i) := HQLsymm.
  by rewrite mxE.
rewrite mxE.
rewrite (bigD1 s)//= mxE eqxx mulr1 big1; last first.
  by move=> j /negPf Hj; rewrite mxE Hj mulr0.
rewrite addr0 entry_eq.
by rewrite -schreier_walk_eq_endpoint.
Qed.

(** wreath_spectral_convergence_proved — the wreath endpoint law is within
    sqrt(14) * alpha^L of uniform.
    Kind: main.
    Why: feeds wreath_spectral_convergence_gap and the SchreierCertificate.
    Proof assembles symm_ds_TV_bound_cV (Q symmetric via wreath_schreier_symm,
    doubly stochastic, Rayleigh via wreath_rayleigh_Qsq_R) with the endpoint
    bridge, exactly as symm_ds_TV_bound does for the involutive case. *)
Lemma wreath_spectral_convergence_proved
    (R : realType) (L : nat) (s : 'I_14) :
  var_dist (fdistmap (fun sigma : {perm 'I_14} => sigma s)
                     (rho_from_words L wreath_sym_gens))
           (fdist_uniform (card_ord 14))
  <= Num.sqrt 14%:R * (wreath_alpha_R R) ^+ L.
Proof.
set Q := schreier_transition R wreath_sym_gens.
have Q_row_sum : forall i : 'I_14, \sum_j Q i j = 1
  by exact: schreier_transition_stochastic.
have Q_col_sum : forall j : 'I_14, \sum_i Q i j = 1
  by exact: wreath_schreier_col_sum.
have Q_symm : Q^T = Q by exact: wreath_schreier_symm.
rewrite /var_dist.
have HtoCol :
  \sum_a `|fdistmap (fun sigma : {perm 'I_14} => sigma s)
            (rho_from_words L wreath_sym_gens) a
        - fdist_uniform (card_ord 14) a|
  = \sum_a `|(Q ^+ L *m \col_i (i == s)%:R) a ord0
            - (\col_i (#|'I_14|%:R^-1 : R)) a ord0|.
  apply: eq_bigr => a _.
  congr `|_|; congr (_ - _).
    rewrite /Q.
    exact: (wreath_schreier_endpoint_eq R L s a).
  by rewrite mxE fdist_uniformE.
rewrite HtoCol.
have HsqrtN_eq : Num.sqrt (14%:R : R) = Num.sqrt (#|'I_14|%:R)
  by rewrite card_ord.
rewrite HsqrtN_eq.
exact: (@symm_ds_TV_bound_cV R 13 Q Q_row_sum Q_col_sum Q_symm
          (wreath_alpha_R R) (wreath_alpha_R_ge0 R)
          (@wreath_rayleigh_Qsq_R R) L s).
Qed.

(******************************************************************************)
(*  Section 6. Spectral-gap form and packaging.                               *)
(******************************************************************************)

(** wreath_gap_R — the wreath spectral gap, 1 - alpha.
    Kind: definition. Why: the gap form consumed by the SchreierCertificate. *)
Definition wreath_gap_R (R : realType) : R := 1 - wreath_alpha_R R.

(** wreath_gap_R_pos — the wreath spectral gap is strictly positive.
    Kind: helper. Why: positivity drives geometric convergence.
    Used by: wreath_schreier_certificate. *)
Lemma wreath_gap_R_pos (R : realType) : 0 < wreath_gap_R R.
Proof. rewrite /wreath_gap_R subr_gt0; exact: wreath_alpha_R_lt1. Qed.

(** wreath_gap_R_le1 — the wreath spectral gap is at most one.
    Kind: helper. Why: with pos, places gap in [0,1].
    Used by: wreath_schreier_certificate. *)
Lemma wreath_gap_R_le1 (R : realType) : wreath_gap_R R <= 1.
Proof.
rewrite /wreath_gap_R lerBlDr addrC -lerBlDr subrr.
exact: wreath_alpha_R_ge0.
Qed.

(** wreath_gap_R_one_minus — the complement of the gap is alpha.
    Kind: helper. Why: algebraic bridge between alpha and 1 - gap.
    Used by: wreath_spectral_convergence_gap. *)
Lemma wreath_gap_R_one_minus (R : realType) :
  1 - wreath_gap_R R = wreath_alpha_R R.
Proof. by rewrite /wreath_gap_R opprB addrA addrAC subrr add0r. Qed.

(** wreath_spectral_convergence_gap — convergence bound in spectral-gap form.
    Kind: main. Why: the exact shape of SchreierCertificate.sc_convergence. *)
Lemma wreath_spectral_convergence_gap
    (R : realType) (L : nat) (s : 'I_14) :
  var_dist (fdistmap (fun sigma : {perm 'I_14} => sigma s)
                     (rho_from_words L wreath_sym_gens))
           (fdist_uniform (card_ord 14))
  <= Num.sqrt 14%:R * (1 - wreath_gap_R R) ^+ L.
Proof.
rewrite wreath_gap_R_one_minus.
exact: wreath_spectral_convergence_proved.
Qed.

(** wreath_schreier_certificate — the Schreier spectral certificate for the
    symmetric wreath walk.
    Kind: instance. Why: packages gap + convergence into the generic record
    that yields a SecurityAsymptotic with floor 0. *)
Definition wreath_schreier_certificate (R : realType) :
    SchreierCertificate R 4 12 wreath_sym_gens :=
  MkSchreierCertificate
    (wreath_gap_R R)
    (wreath_gap_R_pos R)
    (wreath_gap_R_le1 R)
    (fun L s => wreath_spectral_convergence_gap R L s).

(** wreath_asymptotic — the wreath SecurityAsymptotic, additive floor 0.
    Kind: main. Why: THE deliverable; brings the wreath plug to the S_5
    standard (sa_eps_inf = 0, geometric decay). *)
Definition wreath_asymptotic (R : realType) :
    @SecurityAsymptotic R M_wreath_sym :=
  security_witness_schreier_asymptotic (wreath_schreier_certificate R).

(** wreath_asymptotic_eps_inf_zero — the additive floor is 0.
    Kind: main. Why: the headline parity with s5_eps_inf_zero. *)
Lemma wreath_asymptotic_eps_inf_zero (R : realType) :
  sa_eps_inf (wreath_asymptotic R) = 0.
Proof. by []. Qed.

(** wreath_security_witness_schreier — the Schreier-based SecurityWitness at L.
    Kind: instance. Why: the witness carrying Some wreath_asymptotic, ready to
    rewire the wreath plug. Hlfree is word-eval injectivity at length L; the
    asymptotic itself needs none. *)
Definition wreath_security_witness_schreier (R : realType) (L : nat)
    (Hlfree : @weval_inj M_wreath_sym L) : SecurityWitness R M_wreath_sym :=
  security_witness_schreier (wreath_schreier_certificate R) Hlfree.

(** wreath_security_witness_asymptotic — the plug-ready SecurityWitness at L,
    built directly, carrying Some wreath_asymptotic.
    Kind: instance.
    Why: the witness the MonodromyProfile plug consumes. Unlike
    wreath_security_witness_schreier it needs no word-eval injectivity: the
    sw_bound field is wreath_spectral_convergence_gap itself, mirroring
    s5_security_witness_schreier. This is what makes the wreath plug carry an
    asymptotic, matching the S_5 plug. *)
Definition wreath_security_witness_asymptotic (R : realType) (L : nat) :
    SecurityWitness R M_wreath_sym :=
  @MkSecurityWitness R M_wreath_sym L
    (Num.sqrt 14%:R * (1 - wreath_gap_R R) ^+ L)
    (rho_from_words L wreath_sym_gens)
    (fun s => wreath_spectral_convergence_gap R L s)
    None
    (Some (wreath_asymptotic R)).
