(* infotheo (c) AIST and Tohoku University. License: GPL-3.0-or-later. *)
From HB Require Import structures.
From mathcomp Require Import ssreflect ssrbool ssrfun eqtype ssrnat seq.
From mathcomp Require Import div fintype tuple finfun finset fingroup perm.
From mathcomp Require Import morphism action cyclic bigop.
From pgg_smc Require Import pgg_interface.

(******************************************************************************)
(* PGG-SMC: Abelian (Cyclic) Group Instance for MonodromyRepr Mixin          *)
(*                                                                           *)
(* Constructs a MonodromyReprType instance where G = <[sigma]> is a cyclic   *)
(* subgroup of S_N generated by a permutation sigma.                         *)
(*                                                                           *)
(*   ncycle n == the canonical N-cycle (0 1 2 ... N-1) on 'I_(n.+2)         *)
(*   Cyclic_PGGTypes n sigma == PGGTypes record for G = <[sigma]>            *)
(*   Cyclic_isMonodromyRepr == HB instance registering the inclusion morphism *)
(*   Cyclic_PGG_2 n sigma == 2-party PGG_Interface for the cyclic instance   *)
(*   NCycle_PGGTypes n == PGGTypes using the canonical N-cycle               *)
(*   NCycle_PGG_2 n == 2-party PGG_Interface using the canonical N-cycle     *)
(*                                                                           *)
(* Key properties:                                                           *)
(*   cyclic_G_abelian : abelian <[sigma]>                                    *)
(*   ncycle_order : #[ncycle n] = N                                          *)
(*   ncycle_iter : (ncycle n ^+ k) x = (x + k) mod N                        *)
(*                                                                           *)
(* The abelian setting causes security collapse (paper sections 10-12):      *)
(* sigma_P depends only on the frequency vector of generator indices, so     *)
(* one evaluation of the resulting translation determines sigma_P.           *)
(* Formalizing the collapse needs: orbit-regularity + frequency-vector       *)
(* counting — not yet done.                                                  *)
(******************************************************************************)

Set Implicit Arguments.
Unset Strict Implicit.
Import Prenex Implicits.

(* ========================================================================== *)
(* Canonical N-cycle permutation                                              *)
(* ========================================================================== *)

Section ncycle_def.

Variable n : nat.
Let N := n.+2.

Definition shift_fun (i : 'I_N) : 'I_N :=
  Ordinal (ltn_pmod (i.+1) (isT : (0 < N)%N)).

Definition unshift_fun (i : 'I_N) : 'I_N :=
  Ordinal (ltn_pmod (i + n.+1) (isT : (0 < N)%N)).

Lemma shift_unshiftK : cancel shift_fun unshift_fun.
Proof.
move=> i; apply: val_inj => /=.
rewrite modnDml addnC addSn addnS.
by change ((N + i) %% N = i); rewrite modnDl modn_small.
Qed.

Lemma shift_fun_inj : injective shift_fun.
Proof. exact: can_inj shift_unshiftK. Qed.

Definition ncycle : {perm 'I_N} := perm shift_fun_inj.

Lemma ncycleE (i : 'I_N) :
  ncycle i = Ordinal (ltn_pmod (i.+1) (isT : (0 < N)%N)).
Proof. by rewrite /ncycle permE. Qed.

(* Iterated application of the N-cycle *)
Lemma ncycle_iter (k : nat) (x : 'I_N) :
  ((ncycle ^+ k)%g : {perm 'I_N}) x =
  Ordinal (ltn_pmod (x + k) (isT : (0 < N)%N)).
Proof.
elim: k => [|k IHk].
  rewrite expg0 perm1; apply val_inj => /=.
  by rewrite addn0 modn_small.
rewrite expgSr permM IHk ncycleE; apply val_inj => /=.
by rewrite addnS -addn1 modnDml addn1.
Qed.

Lemma ncycle_expN : (ncycle ^+ N = 1 :> {perm 'I_N})%g.
Proof.
apply/permP => x; rewrite ncycle_iter perm1; apply val_inj => /=.
by rewrite modnDr modn_small.
Qed.

(* Full order of the canonical N-cycle *)
Lemma ncycle_order : #[ncycle]%g = N.
Proof.
apply/eqP; rewrite eqn_dvd.
apply/andP; split.
  by rewrite order_dvdn; apply/eqP; exact ncycle_expN.
rewrite /dvdn.
have /permP /(_ ord0) := expg_order ncycle.
rewrite ncycle_iter perm1 => /eqP.
by rewrite -val_eqE /= add0n.
Qed.

End ncycle_def.

(* ========================================================================== *)
(* Cyclic Group Instance for MonodromyRepr                                    *)
(* ========================================================================== *)

Section cyclic_instance.

Variable n : nat.
Let N := n.+2.
Let gT : finGroupType := {perm 'I_N}.

Variable sigma : gT.
Let G : {group gT} := <[sigma]>.

(* Inclusion morphism: identity on the subgroup *)
Lemma incl_morphM : {in G &, {morph (@id gT) : x y / (x * y)%g}}.
Proof. by []. Qed.

Definition incl_morph : {morphism G >-> {perm 'I_N}} :=
  Morphism incl_morphM.

Definition Cyclic_PGGTypes := @MkPGG gT N.-1 G.

HB.instance Definition Cyclic_isMonodromyRepr :=
  @isMonodromyRepr.Build Cyclic_PGGTypes incl_morph.

Definition cyclic_sigmas : 1.-tuple gT := [tuple sigma].

Lemma tnth_cyclic_sigmas (i : 'I_1) : tnth cyclic_sigmas i = sigma.
Proof. by rewrite (tnth_nth sigma) /=; case: i => [[|]]. Qed.

Lemma cyclic_sigmas_gen :
  <<[set tnth cyclic_sigmas i | i : 'I_1]>>%G = G.
Proof.
have -> : [set tnth cyclic_sigmas i | i : 'I_1] = [set sigma]; last by [].
apply/setP => x; rewrite in_set1; apply/idP/idP.
  by move/imsetP => [i _ ->]; rewrite tnth_cyclic_sigmas.
by move/eqP => ->; apply/imsetP; exists ord0 => //; rewrite tnth_cyclic_sigmas.
Qed.

HB.instance Definition Cyclic_hasGenerators :=
  @hasGenerators.Build Cyclic_PGGTypes 0 cyclic_sigmas cyclic_sigmas_gen.

(* Key property: cyclic groups are abelian *)
Lemma cyclic_G_abelian : abelian G.
Proof. exact: cycle_abelian. Qed.

(* Word evaluation in the cyclic (1-generator) instance *)
Lemma cyclic_word_eval (L : nat) (w : @pgg_word Cyclic_PGGTypes L) :
  @word_eval Cyclic_PGGTypes L w = (sigma ^+ L)%g.
Proof.
rewrite /word_eval; under eq_bigr do rewrite tnth_cyclic_sigmas.
by rewrite big_const card_ord iter_mulg_1.
Qed.

(* Search space collapse: at most #[sigma] distinct elements reachable *)
Lemma cyclic_search_space_le (L : nat) :
  @search_space Cyclic_PGGTypes L <= #[sigma]%g.
Proof.
apply: leq_trans (@search_space_leG Cyclic_PGGTypes L) _.
by rewrite /= orderE.
Qed.

(* 2-party interface: starts = [0, 1] *)
Let M : MonodromyReprType := Cyclic_PGGTypes.

Definition cyclic_starts_2 : 2.-tuple 'I_N :=
  [tuple @Ordinal N 0 isT; @Ordinal N 1 isT].

Lemma cyclic_starts_2_uniq : uniq cyclic_starts_2.
Proof. by vm_compute. Qed.

Definition Cyclic_PGG_2 : PGG_Interface M :=
  @MkPGGI M 1 cyclic_starts_2 cyclic_starts_2_uniq.

End cyclic_instance.

(* ========================================================================== *)
(* Concrete instance using the canonical N-cycle                              *)
(* ========================================================================== *)

Section ncycle_instance.

Variable n : nat.
Let N := n.+2.

Definition NCycle_PGGTypes := @Cyclic_PGGTypes n (ncycle n).

Let M : MonodromyReprType := NCycle_PGGTypes.

Definition NCycle_PGG_2 : PGG_Interface M :=
  @Cyclic_PGG_2 n (ncycle n).

End ncycle_instance.
