(* infotheo (c) AIST and Tohoku University. License: GPL-3.0-or-later. *)
From HB Require Import structures.
From mathcomp Require Import ssreflect ssrbool ssrfun eqtype ssrnat seq.
From mathcomp Require Import div fintype tuple finfun finset fingroup perm.
From mathcomp Require Import morphism action cyclic.
From pgg_smc Require Import pgg_interface.

(******************************************************************************)
(* PGG-SMC: Abelian (Cyclic) Group Instance for MonodromyRepr Mixin          *)
(*                                                                           *)
(* Constructs a MonodromyReprType instance where G = <[sigma]> is a cyclic   *)
(* subgroup of S_N generated by a permutation sigma.                         *)
(*                                                                           *)
(*   ncycle n == the canonical N-cycle (0 1 2 ... N-1) on 'I_(n.+2)         *)
(*   Cyclic_PGGTypes n sigma == PGGTypes record for G = <[sigma]>            *)
(*   Cyclic_isMonodromyRepr == HB instance registering the inclusion morphism *)
(*   Cyclic_PGG_2 n sigma == 2-party PGG_Interface for the cyclic instance   *)
(*   NCycle_PGGTypes n == PGGTypes using the canonical N-cycle               *)
(*   NCycle_PGG_2 n == 2-party PGG_Interface using the canonical N-cycle     *)
(*                                                                           *)
(* Key properties:                                                           *)
(*   cyclic_G_abelian : abelian <[sigma]>                                    *)
(******************************************************************************)

Set Implicit Arguments.
Unset Strict Implicit.
Import Prenex Implicits.

(* ========================================================================== *)
(* Canonical N-cycle permutation                                              *)
(* ========================================================================== *)

Section ncycle_def.

Variable n : nat.
Let N := n.+2.

Definition shift_fun (i : 'I_N) : 'I_N :=
  Ordinal (ltn_pmod (i.+1) (isT : (0 < N)%N)).

Definition unshift_fun (i : 'I_N) : 'I_N :=
  Ordinal (ltn_pmod (i + n.+1) (isT : (0 < N)%N)).

Lemma shift_unshiftK : cancel shift_fun unshift_fun.
Proof.
move=> i; apply: val_inj => /=.
rewrite modnDml addnC addSn addnS.
by change ((N + i) %% N = i); rewrite modnDl modn_small.
Qed.

Lemma shift_fun_inj : injective shift_fun.
Proof. exact: can_inj shift_unshiftK. Qed.

Definition ncycle : {perm 'I_N} := perm shift_fun_inj.

Lemma ncycleE (i : 'I_N) :
  ncycle i = Ordinal (ltn_pmod (i.+1) (isT : (0 < N)%N)).
Proof. by rewrite /ncycle permE. Qed.

End ncycle_def.

(* ========================================================================== *)
(* Cyclic Group Instance for MonodromyRepr                                    *)
(* ========================================================================== *)

Section cyclic_instance.

Variable n : nat.
Let N := n.+2.
Let gT : finGroupType := {perm 'I_N}.

Variable sigma : gT.
Let G : {group gT} := <[sigma]>.

(* Inclusion morphism: identity on the subgroup *)
Lemma incl_morphM : {in G &, {morph (@id gT) : x y / (x * y)%g}}.
Proof. by []. Qed.

Definition incl_morph : {morphism G >-> {perm 'I_N}} :=
  Morphism incl_morphM.

Definition Cyclic_PGGTypes := @MkPGG gT N.-1 G.

HB.instance Definition Cyclic_isMonodromyRepr :=
  @isMonodromyRepr.Build Cyclic_PGGTypes incl_morph.

(* Key property: cyclic groups are abelian *)
Lemma cyclic_G_abelian : abelian G.
Proof. exact: cycle_abelian. Qed.

(* 2-party interface: starts = [0, 1] *)
Let M : MonodromyReprType := Cyclic_PGGTypes.

Definition cyclic_starts_2 : 2.-tuple 'I_N :=
  [tuple @Ordinal N 0 isT; @Ordinal N 1 isT].

Lemma cyclic_starts_2_uniq : uniq cyclic_starts_2.
Proof. by vm_compute. Qed.

Definition Cyclic_PGG_2 : PGG_Interface M :=
  @MkPGGI M 1 cyclic_starts_2 cyclic_starts_2_uniq.

End cyclic_instance.

(* ========================================================================== *)
(* Concrete instance using the canonical N-cycle                              *)
(* ========================================================================== *)

Section ncycle_instance.

Variable n : nat.
Let N := n.+2.

Definition NCycle_PGGTypes := @Cyclic_PGGTypes n (ncycle n).

Let M : MonodromyReprType := NCycle_PGGTypes.

Definition NCycle_PGG_2 : PGG_Interface M :=
  @Cyclic_PGG_2 n (ncycle n).

End ncycle_instance.
