(* infotheo (c) AIST and Tohoku University. License: GPL-3.0-or-later. *)
From HB Require Import structures.
From mathcomp Require Import ssreflect ssrbool ssrfun eqtype ssrnat seq.
From mathcomp Require Import div fintype tuple finfun finset fingroup perm.
From mathcomp Require Import morphism action.
From pgg_smc Require Import pgg_interface.

(******************************************************************************)
(* PGG-SMC: Non-Abelian (Star Transposition) Group Instance                  *)
(*                                                                           *)
(* Constructs a MonodromyReprType instance where G = S_{T+1} is the full     *)
(* symmetric group, generated by "star" transpositions σ_i = (0, i+1).       *)
(*                                                                           *)
(* Why not the free group F_T?                                               *)
(*   F_T is infinite and cannot be a finGroupType.  However, a true free     *)
(*   group is not needed for security: the key property is that σ_P          *)
(*   (the monodromy permutation) is close to uniform over S_N, which holds   *)
(*   for ANY non-abelian G via random-walk mixing — not just F_T.  The free  *)
(*   group gives tighter parameters (search space 2r(2r-1)^{L-1} vs (T+1)!) *)
(*   but the security *statement* (row independence) is the same.  The       *)
(*   abelian case breaks because σ_P is constrained to a polynomial-sized    *)
(*   orbit, making row independence fail (see pgg_abelian.v).                *)
(*                                                                           *)
(*   nonab_gen i == tperm ord0 (lift ord0 i), the "star" transposition       *)
(*                  swapping 0 and i+1 in S_N                                *)
(*   nonab_gen_tuple == T.-tuple of star generators                          *)
(*   nonab_gen_noncommute == pairwise non-commutativity of generators        *)
(*   nonab_gen_invol == each generator is an involution (σ_i^2 = 1)          *)
(*   nonab_G_nonabelian == the generated group is non-abelian (when T >= 2)  *)
(*                                                                           *)
(* Note: G = S_{T+1}, NOT F_T — the generators satisfy the involution and   *)
(* braid relations absent in the free group.  The "nonab" prefix is chosen   *)
(* to avoid confusion with a future star-RAAG instance.                      *)
(******************************************************************************)

Set Implicit Arguments.
Unset Strict Implicit.
Import Prenex Implicits.

(* ========================================================================== *)
(* Parameterized multi-generator instance                                     *)
(* ========================================================================== *)

Section generated_instance.

Variable m : nat.
Variable n : nat.
Let T := m.+1.
Let N := n.+2.
Let gT : finGroupType := {perm 'I_N}.

Variable sigmas : T.-tuple gT.

Let gen_set : {set gT} := [set tnth sigmas i | i : 'I_T].
Let G : {group gT} := <<gen_set>>%G.

(* Inclusion morphism: identity on the subgroup *)
Lemma gen_incl_morphM : {in G &, {morph (@id gT) : x y / (x * y)%g}}.
Proof. by []. Qed.

Definition gen_incl_morph : {morphism G >-> {perm 'I_N}} :=
  Morphism gen_incl_morphM.

Definition Gen_PGGTypes := @MkPGG gT N.-1 G.

HB.instance Definition Gen_isMonodromyRepr :=
  @isMonodromyRepr.Build Gen_PGGTypes gen_incl_morph.

Let M : MonodromyReprType := Gen_PGGTypes.

Definition gen_starts_2 : 2.-tuple 'I_N :=
  [tuple @Ordinal N 0 isT; @Ordinal N 1 isT].

Lemma gen_starts_2_uniq : uniq gen_starts_2.
Proof. by vm_compute. Qed.

Definition Gen_PGG_2 : PGG_Interface M :=
  @MkPGGI M 1 gen_starts_2 gen_starts_2_uniq.

End generated_instance.

(* ========================================================================== *)
(* Concrete non-commuting generators: star transpositions                     *)
(* ========================================================================== *)

Section star_transpositions.

Variable m : nat.
Let T := m.+1.
Let N := m.+2.
Let gT : finGroupType := {perm 'I_N}.

(* σ_i = tperm 0 (i+1) — transpositions sharing element 0 *)
Definition nonab_gen (i : 'I_T) : gT :=
  tperm (ord0 : 'I_N) (lift (ord0 : 'I_N) i).

Lemma nonab_gen_neq0 (i : 'I_T) : (ord0 : 'I_N) != lift (ord0 : 'I_N) i.
Proof. by rewrite neq_lift. Qed.

Lemma size_nonab_gen_seq : size (map nonab_gen (enum 'I_T)) == T.
Proof. by rewrite size_map -cardT card_ord. Qed.

Definition nonab_gen_tuple : T.-tuple gT := Tuple size_nonab_gen_seq.

Lemma nonab_gen_tupleE (i : 'I_T) : tnth nonab_gen_tuple i = nonab_gen i.
Proof.
rewrite (tnth_nth (nonab_gen i)) /=.
rewrite (nth_map i); last by rewrite size_enum_ord.
by rewrite nth_ord_enum.
Qed.

(* Each generator is an involution — a relation absent in the free group F_T *)
Lemma nonab_gen_invol (i : 'I_T) : (nonab_gen i ^+ 2 = 1)%g.
Proof. by rewrite /nonab_gen expgS expg1 tperm2. Qed.

(* Key property: star generators pairwise do not commute *)
Lemma nonab_gen_noncommute (i j : 'I_T) :
  i != j -> (nonab_gen i * nonab_gen j != nonab_gen j * nonab_gen i)%g.
Proof.
move=> hij; apply/negP => /eqP Heq.
have := congr1 (fun p : gT => p ord0) Heq.
rewrite !permM /nonab_gen.
rewrite tpermL tpermD; last 2 first.
  - exact: neq_lift.
  - by apply: contra_neq hij => /lift_inj.
rewrite tpermL tpermD; last 2 first.
  - exact: neq_lift.
  - by apply: contra_neq hij => /lift_inj.
by move/lift_inj => /eqP; rewrite (negPf hij).
Qed.

(* The generated group is non-abelian (requires T >= 2, i.e., 0 < m) *)
Lemma nonab_G_nonabelian : 0 < m ->
  let gen_set := [set tnth nonab_gen_tuple i | i : 'I_T] in
  ~~ abelian <<gen_set>>%G.
Proof.
move=> hm /=; rewrite abelian_gen; apply/negP.
rewrite abelianE => /subsetP Hsub.
have j_lt : 1 < T by rewrite /T ltnS.
set j : 'I_T := Ordinal j_lt.
have gi_in : nonab_gen ord0 \in [set tnth nonab_gen_tuple i | i : 'I_T].
  by apply/imsetP; exists ord0 => //; rewrite nonab_gen_tupleE.
have gj_in : nonab_gen j \in [set tnth nonab_gen_tuple i | i : 'I_T].
  by apply/imsetP; exists j => //; rewrite nonab_gen_tupleE.
have hij : (ord0 : 'I_T) != j by rewrite -val_eqE.
have /centP /(_ _ gj_in) := Hsub _ gi_in.
by move=> Hcomm; move/negP: (nonab_gen_noncommute hij); apply; apply/eqP.
Qed.

(* Concrete MonodromyReprType and PGG_Interface *)
Definition Nonab_PGGTypes := @Gen_PGGTypes m m nonab_gen_tuple.

Let M : MonodromyReprType := Nonab_PGGTypes.

Definition Nonab_PGG_2 : PGG_Interface M :=
  @Gen_PGG_2 m m nonab_gen_tuple.

End star_transpositions.
