(******************************************************************************)
(** * DSDP Protocol in Chlipala-Style Coroutine-to-State-Machine Framework    *)
(**                                                                           *)
(** This file documents a potential future direction for expressing the DSDP   *)
(** protocol using the certified coroutine-to-state-machine derivation        *)
(** framework from:                                                           *)
(**                                                                           *)
(**   Ikebuchi, M., Erbsen, A., & Chlipala, A.                               *)
(**   "Certifying Derivation of State Machines from Coroutines"               *)
(**   POPL 2022. ACM, 2022.                                                   *)
(**   http://adam.chlipala.net/papers/CoroutinesPOPL22/                        *)
(**   Code: github.com/mit-plv/                                               *)
(**         certifying-derivation-of-state-machines-from-coroutines            *)
(**                                                                           *)
(** * Motivation                                                              *)
(**                                                                           *)
(** The current workflow to get an FSM from the protocol program is:          *)
(**                                                                           *)
(**   dsdp_pismc.v (monadic program `palice_n`)                               *)
(**       |                                                                   *)
(**       | manual construction (~2200 lines)                                 *)
(**       v                                                                   *)
(**   dsdp_fsm.v (Record `phase_state` + Inductive `phase_trans`              *)
(**               + 9 step-correctness lemmas)                                *)
(**       |                                                                   *)
(**       v                                                                   *)
(**   dsdp_fsm_progress.v (trace characterization from FSM)                   *)
(**                                                                           *)
(** The manual FSM construction is heavy labor (even with AI agents) because  *)
(** every state must be defined as a Record, every transition must be proved   *)
(** correct individually, and the whole thing must be kept in sync with the   *)
(** monadic program. For n parties, the loop unrolling creates O(n) states    *)
(** with repetitive but delicate proofs.                                      *)
(**                                                                           *)
(** The Chlipala framework eliminates this manual step entirely: a Coq tactic *)
(** ("derive") compiles the monadic program into an explicit state machine    *)
(** and simultaneously produces an equivalence proof. The output is:          *)
(**   - state : Set (auto-generated, one "variant" per yield point)           *)
(**   - step  : state -> eff -> rets -> state + ret_type (transition fn)      *)
(**   - equiv : the state machine faithfully simulates the coroutine          *)
(**                                                                           *)
(******************************************************************************)
(**                                                                           *)
(** * Framework Overview                                                      *)
(**                                                                           *)
(** ** Core type: free monad over effects                                     *)
(**                                                                           *)
(**   The program type is a free monad indexed by an effect signature:        *)
(**                                                                           *)
(**     Inductive t (ret_type : Set) :=                                       *)
(**     | Eff : forall (e : eff), args e -> (rets e -> t ret_type)            *)
(**                                         -> t ret_type                     *)
(**     | Return : ret_type -> t ret_type.                                    *)
(**                                                                           *)
(**   where:                                                                  *)
(**   - eff      : Set of effect names (e.g., send, recv)                     *)
(**   - args e   : argument type for effect e                                 *)
(**   - rets e   : return type for effect e                                   *)
(**   - Eff e a k: "perform effect e with argument a, bind result to k"       *)
(**   - Return v : "done, return v"                                           *)
(**                                                                           *)
(**   Monadic bind is a fixpoint:                                             *)
(**                                                                           *)
(**     Fixpoint bind (x : t T)(p : T -> t S) :=                             *)
(**       match x with                                                        *)
(**       | Return v => p v                                                   *)
(**       | Eff e a q => Eff e a (fun b => bind (q b) p)                     *)
(**       end.                                                                *)
(**     Notation "x <<- p ; e" := (bind p (fun x => e)).                     *)
(**                                                                           *)
(** ** Coroutines communicate via yield                                       *)
(**                                                                           *)
(**   A coroutine has type:                                                   *)
(**     t (const_yield A) (const_yield B) C                                   *)
(**   meaning it yields values of type A, receives values of type B,          *)
(**   and eventually returns a value of type C.                               *)
(**                                                                           *)
(**   Notation:                                                               *)
(**     v1 <- yield v2 ; e    (* yield v2 out, receive v1 back *)            *)
(**     n <- resume c $ x ; e (* parent resumes child c with input x *)      *)
(**                                                                           *)
(** ** State machine type (the compilation target)                            *)
(**                                                                           *)
(**   Definition step_type (ret_type state : Set) :=                          *)
(**     state -> forall (e : eff), rets e ->                                  *)
(**       (state * option { e : eff & args e }) + ret_type.                   *)
(**                                                                           *)
(**   Given current state and the return of the previous effect, produce:     *)
(**   - inl (next_state, Some (next_effect)) -- continue                      *)
(**   - inl (next_state, None)               -- halted/waiting                *)
(**   - inr return_value                     -- terminated                    *)
(**                                                                           *)
(** ** Compilation: three tactic entry points                                 *)
(**                                                                           *)
(**   derive' env   -- compile program with no coroutines (effects only)      *)
(**   derive_coro env -- compile a child coroutine (yield-based)              *)
(**   derive env    -- compile a parent that uses coroutines                  *)
(**                                                                           *)
(**   The env argument is a tuple of free variables: tt for none,             *)
(**   (tt, n) for one, (tt, fuel, certs, priv) for multiple.                 *)
(**                                                                           *)
(**   After Defined, extract via:                                             *)
(**     Definition my_step := projT1 (projT2 my_derive).                     *)
(**                                                                           *)
(** ** Recursion constraint                                                   *)
(**                                                                           *)
(**   The tactic only knows how to compile these specific loop forms:         *)
(**   - nat_rect_nondep (bounded iteration over nat)                          *)
(**   - list_rec_nondep (iteration over a list)                               *)
(**   Arbitrary Fixpoint/fix are NOT supported. This is a hard constraint.    *)
(**                                                                           *)
(** ** TLS 1.3 example (200+ line real protocol)                              *)
(**                                                                           *)
(**   The paper demonstrates the framework on a TLS 1.3 server handshake.    *)
(**   Effects are defined as flat inductive types (args_tls / rets_tls).      *)
(**   Each protocol operation (RecvClientHello, SendPacket, etc.) gets a      *)
(**   sugared notation wrapping the raw Eff + pattern matching:               *)
(**                                                                           *)
(**   Notation "r <- 'yield' 'RecvClientHello' ; p" :=                       *)
(**     (Eff yield (recvPacket RClientHello)                                  *)
(**          (fun r' => option_branch                                         *)
(**              (fun r => p)                                                 *)
(**              (fun al => Eff yield (closeWith al)                          *)
(**                             (fun _ => Return None))                       *)
(**              (fromRecvClientHello r'))).                                  *)
(**                                                                           *)
(**   The TLS handshake compiles via:                                         *)
(**                                                                           *)
(**   Lemma doHandshake_derive :                                              *)
(**     { state & { step &                                                    *)
(**       forall fuel certs priv,                                             *)
(**         { init | @equiv_coro _ _ _ _ _ state step init                    *)
(**                              (doHandshake fuel certs priv) } } }.         *)
(**   Proof.                                                                  *)
(**     do 3 eexists. unfold doHandshake. intros.                             *)
(**     Time unshelve derive_coro (tt,fuel,certs,priv);                       *)
(**       intros; exact inhabitant.                                           *)
(**   Time Defined.                                                           *)
(**                                                                           *)
(******************************************************************************)
(**                                                                           *)
(** * Translation of DSDP Alice into Chlipala Style                           *)
(**                                                                           *)
(** Below we show how Alice's n-party DSDP protocol would be expressed        *)
(** in the Chlipala free-monad + derive framework, contrasted with the        *)
(** current piSMC representation.                                             *)
(**                                                                           *)
(** ** Current piSMC representation (from dsdp_pismc.v)                       *)
(**                                                                           *)
(**   Definition palice_n                                                     *)
(**       (relays : seq 'I_n_relay.+1)                                        *)
(**       (dk : priv_keyT) (v0 : msgT)                                        *)
(**       (u : 'I_n_relay.+2 -> msgT)                                         *)
(**       (r : 'I_n_relay.+1 -> msgT)                                         *)
(**       (rand_a : 'I_n_relay.+1 -> randT)                                   *)
(**       : sproc dsdp_dtype data alice_idx :=                                *)
(**     \pi{ Init (#dk, &v0) ;                                                *)
(**        ForList relays step (fun k => k.+2) enstep alice_env_step          *)
(**          as j cont k =>                                                   *)
(**          Recv<(j.+1)> c =>                                                *)
(**          Send<(alice_send_dest j)>                                         *)
(**            $(c ^h (u (lift ord0 j))                                        *)
(**                *h (enc_pub_key j.+1 (r j) (rand_a j))) ;                  *)
(**          k                                                                *)
(**        end ;                                                              *)
(**        Recv<(n_relay.+1)> #dk g =>                                        *)
(**        Ret &(g - \sum_(j < n_relay.+1) r j + u ord0 * v0) }.             *)
(**                                                                           *)
(** ** Step 1: Define DSDP communication effects                              *)
(**                                                                           *)
(**   In Chlipala's framework, every I/O operation is an "effect" in a        *)
(**   free monad. We define an enumeration of effect names, plus functions    *)
(**   mapping each effect to its argument and return types.                    *)
(**                                                                           *)
(**   Inductive dsdp_eff :=                                                   *)
(**     | eff_init_key    (* store private key in local state *)              *)
(**     | eff_init_val    (* store initial plaintext *)                       *)
(**     | eff_recv_enc    (* receive a ciphertext from party j *)             *)
(**     | eff_send_enc    (* send a ciphertext to party dest *)              *)
(**     | eff_recv_dec    (* receive + decrypt from last relay *)             *)
(**     | eff_ret.        (* return the final plaintext value *)              *)
(**                                                                           *)
(**   Definition dsdp_args (e : dsdp_eff) : Set :=                            *)
(**     match e with                                                          *)
(**     | eff_init_key   => priv_keyT                                         *)
(**     | eff_init_val   => msgT                                              *)
(**     | eff_recv_enc   => nat            (* source party index *)           *)
(**     | eff_send_enc   => nat * encT     (* dest party, ciphertext *)      *)
(**     | eff_recv_dec   => nat * priv_keyT (* source, decryption key *)     *)
(**     | eff_ret        => msgT                                              *)
(**     end.                                                                  *)
(**                                                                           *)
(**   Definition dsdp_rets (e : dsdp_eff) : Set :=                            *)
(**     match e with                                                          *)
(**     | eff_recv_enc   => encT    (* received ciphertext *)                *)
(**     | eff_recv_dec   => msgT    (* decrypted plaintext *)                *)
(**     | _              => unit                                              *)
(**     end.                                                                  *)
(**                                                                           *)
(** ** Step 2: Sugared notations                                              *)
(**                                                                           *)
(**   Each effect gets a notation that hides the raw Eff constructor:         *)
(**                                                                           *)
(**   Notation "'InitKey' dk ; p" :=                                          *)
(**     (Eff eff_init_key dk (fun _ => p))                                    *)
(**     (at level 200).                                                       *)
(**   Notation "'InitVal' v ; p" :=                                           *)
(**     (Eff eff_init_val v (fun _ => p))                                     *)
(**     (at level 200).                                                       *)
(**   Notation "c <- 'RecvEnc' j ; p" :=                                     *)
(**     (Eff eff_recv_enc j (fun c => p))                                     *)
(**     (at level 100, right associativity).                                  *)
(**   Notation "'SendEnc' dest val ; p" :=                                   *)
(**     (Eff eff_send_enc (dest, val) (fun _ => p))                          *)
(**     (at level 200).                                                       *)
(**   Notation "g <- 'RecvDec' j dk ; p" :=                                  *)
(**     (Eff eff_recv_dec (j, dk) (fun g => p))                              *)
(**     (at level 100, right associativity).                                  *)
(**   Notation "'RetVal' v" :=                                                *)
(**     (Eff eff_ret v (fun _ => Return tt))                                 *)
(**     (at level 200).                                                       *)
(**                                                                           *)
(** ** Step 3: Alice as a coroutine                                           *)
(**                                                                           *)
(**   The protocol is a function returning the free monad type.               *)
(**   The loop MUST use nat_rect_nondep (the tactic's supported loop form),  *)
(**   not ForList or arbitrary fixpoints.                                     *)
(**                                                                           *)
(**   Definition alice_n (n_relay : nat)                                      *)
(**       (dk : priv_keyT) (v0 : msgT)                                        *)
(**       (u : 'I_n_relay.+2 -> msgT)                                         *)
(**       (r : 'I_n_relay.+1 -> msgT)                                         *)
(**       (rand_a : 'I_n_relay.+1 -> randT)                                   *)
(**       : t dsdp_args dsdp_rets unit :=                                     *)
(**     InitKey dk ;                                                          *)
(**     InitVal v0 ;                                                          *)
(**     (* recv/send loop over relays *)                                      *)
(**     nat_rect_nondep (fun _ => t dsdp_args dsdp_rets unit)                *)
(**       (* base case: after all relays, receive final result *)             *)
(**       (g <- RecvDec n_relay.+1 dk ;                                       *)
(**        RetVal (g - \sum_(j < n_relay.+1) r j + u ord0 * v0))             *)
(**       (* step case: recv from relay j+1, send masked ciphertext *)        *)
(**       (fun j cont =>                                                      *)
(**          c <- RecvEnc j.+1 ;                                              *)
(**          SendEnc (maxn 1 j)                                               *)
(**            (c ^h (u (lift ord0 j))                                        *)
(**               *h enc_pub_key j.+1 (r j) (rand_a j)) ;                    *)
(**          cont)                                                            *)
(**       n_relay.+1.                                                         *)
(**                                                                           *)
(**   Note: nat_rect_nondep counts down from n_relay.+1 to 0, applying       *)
(**   the step case at each level, which builds up the recv/send chain.       *)
(**   The iteration order matches ForList over [ord0; ...; ord_max].          *)
(**                                                                           *)
(** ** Step 4: Auto-derive the FSM (the key benefit)                          *)
(**                                                                           *)
(**   Lemma alice_n_derive :                                                  *)
(**     { state & { step & forall n_relay dk v0 u r rand_a,                   *)
(**       { init | @equiv _ _ _ _ state step init                             *)
(**                        (alice_n n_relay dk v0 u r rand_a) }}}.            *)
(**   Proof.                                                                  *)
(**     do 3 eexists.                                                         *)
(**     unfold alice_n.                                                       *)
(**     unshelve derive' (tt, n_relay, dk, v0, u, r, rand_a);                *)
(**       exact inhabitant.                                                   *)
(**   Defined.                                                                *)
(**                                                                           *)
(**   (* Extract the auto-generated state machine *)                          *)
(**   Definition alice_state := projT1 alice_n_derive.                        *)
(**   Definition alice_step  := projT1 (projT2 alice_n_derive).               *)
(**                                                                           *)
(**   After Defined, Coq automatically produces:                              *)
(**   - alice_state : an inductive/nested-sum type with one "variant"         *)
(**     per yield point (= per Eff constructor in the unrolled program).      *)
(**     This is analogous to our manual phase_state Record values             *)
(**     (st_init1, st_recv j, st_send j, etc.) but auto-generated.           *)
(**   - alice_step : the transition function, analogous to our manual         *)
(**     phase_trans inductive + 9 step_ok_* lemmas, but auto-generated.      *)
(**   - equiv proof: the state machine faithfully simulates the coroutine,    *)
(**     analogous to our manual phase_trans_step_ok, but auto-generated.      *)
(**                                                                           *)
(******************************************************************************)
(**                                                                           *)
(** * Side-by-Side Comparison                                                 *)
(**                                                                           *)
(**   | Aspect         | piSMC (palice_n)          | Chlipala (alice_n)      *)
(**   |----------------|---------------------------|-------------------------*)
(**   | Syntax         | \pi{...} DSL with         | Free monad + notations  *)
(**   |                | Recv<j>, Send<dest>       | RecvEnc j, SendEnc d v  *)
(**   |                |                           |                         *)
(**   | Loop form      | ForList relays step ...   | nat_rect_nondep         *)
(**   |                | as j cont k => ... k end  | (fun j cont => ...)     *)
(**   |                |                           |                         *)
(**   | Session types  | Yes (sproc tracks env,    | No (effects are         *)
(**   |                | duality by native_compute)| untyped w.r.t. session) *)
(**   |                |                           |                         *)
(**   | FSM derivation | Manual: ~2200 lines of    | Automatic: ~10 lines    *)
(**   |                | Records + inductive +     | (derive' tactic)        *)
(**   |                | step-correctness lemmas   |                         *)
(**   |                |                           |                         *)
(**   | Equivalence    | Hand-proved               | Auto-proved (bundled    *)
(**   | proof          | phase_trans_step_ok       | in derive' output)      *)
(**   |                |                           |                         *)
(**   | State names    | Explicit: st_recv j,      | Opaque: nested          *)
(**   |                | st_send j, st_tail rr     | sum/product type        *)
(**   |                |                           |                         *)
(**   | Readability    | High (session-type DSL    | Medium (free monad is   *)
(**   |                | close to protocol paper)  | standard but loops are  *)
(**   |                |                           | nat_rect_nondep)        *)
(**   |                |                           |                         *)
(**   | Flexibility    | Full control over state   | State type is opaque    *)
(**   |                | representation            | (tactic-generated)      *)
(**                                                                           *)
(******************************************************************************)
(**                                                                           *)
(** * Pros                                                                    *)
(**                                                                           *)
(** 1. Eliminates ~2200 lines of manual FSM construction per protocol.        *)
(**    The derive tactic produces state + step + equivalence proof             *)
(**    automatically from the monadic program in ~10 lines.                   *)
(**                                                                           *)
(** 2. The protocol program IS the single source of truth. No risk of the     *)
(**    FSM drifting out of sync with the program (a real maintenance burden   *)
(**    in the current approach, especially when parameters change).            *)
(**                                                                           *)
(** 3. Demonstrated on real protocols. The TLS 1.3 server handshake in the   *)
(**    paper is 200+ lines of protocol logic — comparable in complexity to    *)
(**    our n-party DSDP Alice.                                                *)
(**                                                                           *)
(** 4. Composable via coroutine hierarchy. Child coroutines (sub-protocols)  *)
(**    can be compiled separately with derive_coro, then the parent uses     *)
(**    let_coro/resume to compose them. Each sub-protocol gets its own        *)
(**    state machine, and the parent's derive tactic uses Hint Resolve to     *)
(**    find pre-compiled children:                                            *)
(**                                                                           *)
(**      Hint Resolve child_equiv : equivc.                                   *)
(**      (* parent's derive automatically picks up the child's SM *)          *)
(**                                                                           *)
(**    This would let us compile each relay template (DParty_first,           *)
(**    DParty_intermediate, DParty_last) as a separate coroutine and          *)
(**    compose them with Alice's coroutine.                                   *)
(**                                                                           *)
(** 5. The free monad representation is standard and well-understood.         *)
(**    Effect signatures (dsdp_eff, dsdp_args, dsdp_rets) are simple          *)
(**    datatypes that can be reused across multiple protocols.                 *)
(**                                                                           *)
(******************************************************************************)
(**                                                                           *)
(** * Cons                                                                    *)
(**                                                                           *)
(** 1. Opaque state types. The auto-generated state is a nested sum/product  *)
(**    type, not named states like st_recv(j). Downstream proofs that need   *)
(**    to reason about "which state are we in" (e.g., trace                   *)
(**    characterization in dsdp_fsm_progress.v, security in                   *)
(**    dsdp_security.v) would need to pattern-match on this opaque type.     *)
(**    This could make those proofs HARDER, not easier — we might end up     *)
(**    needing to re-derive named state wrappers anyway.                      *)
(**                                                                           *)
(** 2. Loop syntax is less readable. nat_rect_nondep (or list_rec_nondep)    *)
(**    is the ONLY supported loop form — the tactic cannot handle arbitrary  *)
(**    fixpoints or our ForList combinator. This is a hard constraint.        *)
(**    Compare:                                                               *)
(**                                                                           *)
(**      (* piSMC — reads like pseudocode *)                                  *)
(**      ForList relays step ... as j cont k =>                               *)
(**        Recv<(j.+1)> c =>                                                  *)
(**        Send<(alice_send_dest j)> $(...) ;                                 *)
(**        k                                                                  *)
(**      end                                                                  *)
(**                                                                           *)
(**      (* Chlipala — reads like a fold *)                                   *)
(**      nat_rect_nondep (fun _ => t dsdp_args dsdp_rets unit)               *)
(**        (base_case)                                                        *)
(**        (fun j cont => c <- RecvEnc j.+1 ; SendEnc (...) ; cont)          *)
(**        n_relay.+1                                                         *)
(**                                                                           *)
(** 3. No session types. The piSMC approach tracks send/recv environments    *)
(**    in the type (sproc dsdp_dtype data party) and verifies channel         *)
(**    duality via native_compute. The Chlipala free monad has no built-in   *)
(**    session typing — effects are "fire and forget" with no static check   *)
(**    that sends/recvs match across parties.                                 *)
(**                                                                           *)
(** 4. n-party parametricity is untested. The TLS example in the paper is    *)
(**    a fixed 2-party protocol. Our alice_n is parametric in n_relay —      *)
(**    the number of loop iterations (and hence FSM states) depends on a     *)
(**    runtime parameter. While nat_rect_nondep handles this in principle,   *)
(**    the derived state machine would contain the nat recursion in its       *)
(**    state type, and it's unclear how well this works for large n or        *)
(**    whether the tactic's performance degrades.                             *)
(**                                                                           *)
(** 5. Integration with MathComp/infotheo. The framework uses its own        *)
(**    Inhabit typeclass and targets standard Coq types. Bridging to          *)
(**    MathComp finType, ordinals ('I_n), bigops (\sum_), and our HE         *)
(**    operations (Epow, Emul, enc) would require non-trivial glue code.     *)
(**    In particular, 'I_n_relay.+1 as a loop index would need to be         *)
(**    converted to nat for nat_rect_nondep and back for the HE operations.  *)
(**                                                                           *)
(** 6. Derive tactic is a black box. If it fails (e.g., due to universe      *)
(**    issues, unsupported term shapes, or MathComp compatibility), the       *)
(**    error messages are typically unhelpful and debugging requires deep     *)
(**    understanding of the tactic internals.                                 *)
(**                                                                           *)
(** 7. The framework has not been maintained since 2022. The repository       *)
(**    (github.com/mit-plv/certifying-derivation-of-state-machines-           *)
(**    from-coroutines) targets Coq 8.13. Porting to Rocq 9.0 + MathComp    *)
(**    2.x would be a non-trivial upfront cost.                               *)
(**                                                                           *)
(******************************************************************************)
(**                                                                           *)
(** * Verdict                                                                 *)
(**                                                                           *)
(** The Chlipala approach eliminates the ~2200-line manual FSM construction  *)
(** (the main pain point), but trades it for:                                *)
(**   - Less readable loop syntax (nat_rect_nondep vs ForList)               *)
(**   - Opaque state types that may complicate downstream trace/security      *)
(**     proofs (the states are unnamed nested sums, not st_recv(j))           *)
(**   - Loss of session-type duality checking                                 *)
(**   - Integration effort with MathComp + porting from Coq 8.13             *)
(**                                                                           *)
(** The biggest open question: is the auto-derived FSM usable for            *)
(** downstream trace characterization and security proofs, or would the      *)
(** opaque states force us to re-derive named states anyway — negating       *)
(** the benefit?                                                             *)
(**                                                                           *)
(** A promising middle ground might be to use the Chlipala framework for     *)
(** the INITIAL derivation (getting the state machine structure for free),    *)
(** then wrap the opaque states with named definitions and prove they         *)
(** correspond to the auto-generated states. This would still save most of   *)
(** the ~1000 lines of step-correctness proofs while giving us named states  *)
(** for downstream reasoning.                                                *)
(**                                                                           *)
(** Alternatively, one could extend the framework with a "state naming"      *)
(** pass that lets the user annotate yield points with names, which the       *)
(** tactic would propagate into the generated state type. This would be      *)
(** a contribution to the framework itself.                                   *)
(**                                                                           *)
(******************************************************************************)
