(* infotheo: information theory and error-correcting codes in Rocq            *)
(* Copyright (C) 2025 infotheo authors, license: LGPL-2.1-or-later            *)
(******************************************************************************)
(* probe_f_mutation: the facade and manifest mutations of section 15.8.      *)
(*                                                                            *)
(* Probe unit F of the 2026-08-12 layered-protocol-packing gate.  Three       *)
(* parts:                                                                     *)
(*                                                                            *)
(*   (a) an endpoint marginal bound cannot satisfy the witness required for a *)
(*       Security-bridged path;                                               *)
(*   (b) deleting or retyping a listed alias breaks the manifest checker;     *)
(*   (c) the phase-H2 inventory of every live MonodromyProfile constructor,   *)
(*       generated by a reproducible repository search.                       *)
(*                                                                            *)
(* The file imports the manifest only, exactly as a client would.             *)
(******************************************************************************)

From lpp_probe Require Import probe_f_manifest.

Set Implicit Arguments.
Unset Strict Implicit.
Import Prenex Implicits.
Import GRing.Theory Num.Theory.

Local Open Scope fdist_scope.
Local Open Scope proba_scope.
Local Open Scope ring_scope.

(******************************************************************************)
(*     (a) An endpoint marginal bound is not a security bridge                *)
(*                                                                            *)
(* The witness a Security-bridged path needs, at the five-card carriers, has  *)
(* the shape of the PGL(2,7) coalition bound: a variation distance between    *)
(* the pushforwards of ONE distribution along TWO readers that differ only in *)
(* the secret, bounded by a constant.  fc_bridge_required writes that shape   *)
(* at the seven-cut model: the distribution is the model's own cut            *)
(* distribution, the reader is the decoded colour sequence of the facade, and *)
(* the two committed pairs play the role of the two secrets.                  *)
(*                                                                            *)
(* The seven-cut path proves nothing of that shape.  What it proves is        *)
(* fa_kim_deal_centi_lt, a statement about the distance from uniform of ONE   *)
(* seat's endpoint distribution, quantified over a card position and not over *)
(* a coalition or a pair of secrets.  Mutation M1 tries to use the bound as   *)
(* the bridge and is rejected.                                                *)
(******************************************************************************)

(* fc_bridge_required — the coalition-view indistinguishability statement a
   Security-bridged five-card path would have to exhibit.
   @intent: the PGL(2,7) bridge shape transported to the five-card carriers,
   used only as the target type of mutation M1. *)
Definition fc_bridge_required (R : realType) : Prop :=
  forall (A : seq nat) (ab ab' : bool * bool),
    var_dist
      (fdistmap
         (fun g => @fa_five_card_colour_view R (1 / 100)
            (five_card_kim.kim_centi_lt R) (five_card_kim.kim_centi_gt R)
            (five_card_kim.kim_centi_spec R) 7 A ab g)
         (sa_cut_dist (fa_kim_centi_repeated_sample R)))
      (fdistmap
         (fun g => @fa_five_card_colour_view R (1 / 100)
            (five_card_kim.kim_centi_lt R) (five_card_kim.kim_centi_gt R)
            (five_card_kim.kim_centi_spec R) 7 A ab' g)
         (sa_cut_dist (fa_kim_centi_repeated_sample R)))
    <= 2%:R^-39.

(* M1: the seven-cut endpoint marginal bound offered as the bridge witness.
   Harvested verbatim (batch rocq compile does not echo Fail messages, so the
   command was unwrapped in a scratch copy to capture this):

     Error:
     In environment
     R : realType
     The term "fa_kim_deal_centi_lt R" has type
      "forall s : 'I_5,
       var_dist
         (fdistmap ((fun_of_perm (T:='I_5))^~ s)
            (sw_rho_dist (five_card_kim.kim_security_witness_centi R)))
         (fdist_uniform (card_ord 5)) <
       2 ^- 40"
     while it is expected to have type "fc_bridge_required R"
     (cannot unify "seq nat" and "'I_5").

   The last line is the whole point: the bound quantifies over ONE card
   position, the bridge over a list of positions read by a coalition.  The
   two are not the same statement and no coercion relates them. *)
Fail Definition mutation_bound_as_bridge (R : realType) : fc_bridge_required R
  := @fa_kim_deal_centi_lt R.

(* M1 positive control: the shape is not vacuous, and the PGL(2,7) transfer
   corollary really does inhabit the corresponding PGL bridge type, which is
   the type of the landed word-view theorem itself. *)
Check (alias_same_type fa_pgl27_transfer fa_pgl27_word_view_indist).

(* M1b: the same rejection stated at the type level, with no five-card
   carriers involved.  An endpoint marginal bound and a coalition-view
   indistinguishability bridge do not share a type.  Harvested verbatim:

     Error:
     The term "fa_pgl27_word_view_indist" has type
      "forall (R : realType) (C : {set 'I_8}) (s s' : bool),
       #|C| <= 3 ->
       (var_dist
          (fdistmap (fun g => pgl27_secrecy.pgl27_view R C (s, g))
             (pgl27_word_privacy.rho_word R))
          (fdistmap (fun g => pgl27_secrecy.pgl27_view R C (s', g))
             (pgl27_word_privacy.rho_word R)) <=
        2 ^- 39)%R"
     while it is expected to have type
      "forall (R : realType) (s : 'I_5),
       (var_dist
          (fdistmap ((fun_of_perm (T:='I_5))^~ s)
             (sw_rho_dist (five_card_kim.kim_security_witness_centi R)))
          (fdist_uniform (card_ord 5)) <
        2 ^- 40)%R"
     (cannot unify "'I_5" and "{set 'I_8}").

   Three differences are visible at once: the missing coalition quantifier,
   the missing pair of secrets, and the strict-versus-non-strict comparison
   against a different constant. *)
Fail Check (alias_same_type fa_kim_deal_centi_lt fa_pgl27_word_view_indist).

(* M1c: nor does the spectral endpoint bound, which is the other member of
   the bound sub-block. *)
Fail Check (alias_same_type fa_fc_kim_security_bound fa_pgl27_word_view_indist).

(* M1 positive control, second form: the two five-card sample models that DO
   share a type share it, so the M1b and M1c failures are about the security
   statements and not about five-card values in general. *)
Check (alias_same_type fa_kim_single_sample fa_kim_repeated_sample).

(******************************************************************************)
(*     (b) Deleting or retyping a listed alias breaks the manifest checker     *)
(*                                                                            *)
(* The manifest's checker block is one Check per alias named in a column of   *)
(* its table.  A deleted alias makes the corresponding Check in               *)
(* probe_f_manifest.v fail at elaboration with "The reference ... was not     *)
(* found in the current environment", and because that block sits in the      *)
(* manifest source rather than in a client, probe_f_manifest.v is the file    *)
(* that stops compiling; every downstream file, this one included, then fails *)
(* to Require it.  The two lines below reproduce both halves of that failure  *)
(* mode without editing the manifest: an absent name, and a present name at   *)
(* the wrong type.                                                            *)
(******************************************************************************)

(* M2: an alias that does not exist.  This is what the manifest sees after a
   facade alias is deleted; the failing line is the checker line that names
   it, in the checker block at the foot of probe_f_manifest.v, and the
   message is

     The reference fa_nonexistent_alias was not found in the current
     environment.

   The same message with fa_pgl27_transfer in place of the invented name was
   produced by an interactive session whose flags lacked the lpp_probe root,
   which is the same failure the manifest would show for a deleted alias. *)
Fail Check (fa_nonexistent_alias).

(* M3: an alias that exists at the wrong type, which is what a retyped alias
   looks like to the checker.  fa_pgl27_sample is the exact-uniform model;
   the finite-word row's checker line demands the extra Boolean prior.
   Harvested verbatim:

     Error:
     The term "fa_pgl27_sample" has type
      "forall R : realType, SampleAdapter (pgl27_exec.pgl27_exec_plug R)"
     while it is expected to have type
      "forall R : realType,
       {fdist bool} -> SampleAdapter (fa_pgl27_exec_plug R)"
     (cannot unify "SampleAdapter (pgl27_exec.pgl27_exec_plug R)" and
     "{fdist bool} -> SampleAdapter (fa_pgl27_exec_plug R)").

   The message prints the landed target under its QUALIFIED name, which is a
   second confirmation of the client-visibility finding: the alias retains the
   landed type, and the landed name is reachable from here only qualified. *)
Fail Check (fa_pgl27_sample :
  forall R : realType, R.-fdist bool -> SampleAdapter (fa_pgl27_exec_plug R)).

(* M3 positive control: the same line at the alias the row actually names. *)
Check (fa_pgl27_word_sample :
  forall R : realType, R.-fdist bool -> SampleAdapter (fa_pgl27_exec_plug R)).

(******************************************************************************)
(*     (c) The phase-H2 inventory                                             *)
(*                                                                            *)
(* Reproducible search, run at HEAD 995e2a39 from the repository root:        *)
(*                                                                            *)
(*   grep -rnE 'MkMonodromyProfile|: MonodromyProfile' pgg-smc --include=*.v  *)
(*                                                                            *)
(* Twenty-one hits.  Classification:                                          *)
(*                                                                            *)
(* FIVE DIRECT CONSTRUCTOR SITES (each applies MkMonodromyProfile):           *)
(*   1. abel_profile        abelian/abel_profile.v:69-71                      *)
(*   2. five_card_profile   kim2025/five_card_family.v:166-168                *)
(*   3. pgl27_profile       pgl27/pgl27_profile.v:105-106                     *)
(*   4. s5_profile          s5/s5_profile.v:51-53                             *)
(*   5. s5x5_profile        s5x5/s5x5_profile.v:42-44                         *)
(*                                                                            *)
(* TWO WRAPPERS (each a partial application of five_card_profile):            *)
(*   6. den_boer_profile    denboer1989/den_boer_profile.v:76-78              *)
(*      = five_card_profile at bias zero and word length one; LIVE.           *)
(*   7. kim_profile         kim2025/rigidity_kim_instance.v:66-67             *)
(*      = five_card_profile at the section bias and word length L; ORPHANED,  *)
(*      zero references outside its own file.                                 *)
(*                                                                            *)
(* FOURTEEN FALSE POSITIVES, all of them the TYPE MonodromyProfile appearing  *)
(* in a binder rather than a value being built:                               *)
(*   the record declaration itself, protocol/pgg_monodromy_profile.v:49;      *)
(*   three section variables, pgg_monodromy_profile.v:64,                      *)
(*     pgg_execution_plug.v:117, pgg_sample_adapter.v:130;                     *)
(*   two record parameters, pgg_execution_plug.v:57,                           *)
(*     pgg_sample_adapter.v:114;                                              *)
(*   two definition parameters, pgg_execution_plug.v:78 and :95;               *)
(*   two local Let abbreviations, pgl27/pgl27_exec.v:89 and                    *)
(*     kim2025/five_card_exec.v:122;                                          *)
(*   and the return-type annotations of entries 2, 3, 4, 5 and 7 above,       *)
(*   which the same grep reports a second time.                               *)
(*                                                                            *)
(* Cross-check against migration-inventory.md, "MonodromyProfile values       *)
(* (complete)": that table lists exactly these seven values with the same     *)
(* sites and the same liveness verdicts, and adds the mp_security argument of *)
(* each.  The two documents agree; no profile is missing from either.  The    *)
(* inventory also records that NO monster, oc, cyclic, star or wreath         *)
(* MonodromyProfile exists, which this grep confirms by omission.             *)
(*                                                                            *)
(*     Proposed H2 order                                                      *)
(*                                                                            *)
(* 1. The five-card family, already H1-adjacent.  den_boer_profile is a       *)
(*    partial application of five_card_profile, so the den Boer rows fold     *)
(*    into probe_f_five_card_facade as extra rows rather than a new file;     *)
(*    kim_profile is retired or given a reference before it is faced.         *)
(* 2. s5, then s5x5.  Both are near-orphan profiles with no ExecutionPlug     *)
(*    and no SampleAdapter, so their facades stop at level Algebraic and      *)
(*    their sections 2 to 7 are all documented as empty.                      *)
(* 3. abelian.  A profile exists, so it is recorded in the manifest, but      *)
(*    pgg-smc/instances/ is restricted to kim2025, denboer1989, s5 and s5x5,  *)
(*    so abel_profile is recorded and NOT given a facade.                     *)
(* 4. The rigidity-only instances oc, monster, cyclic and star are NOT        *)
(*    facade-eligible: no MonodromyProfile value exists for any of them, so   *)
(*    they have no level to assign and no program layer to expose.  star is   *)
(*    additionally not in _CoqProject and carries an Admitted.                *)
(*                                                                            *)
(* No step above manufactures execution or security work to raise a level,    *)
(* as section 13.4 requires.                                                  *)
(******************************************************************************)

(* Documentation of the search, as a compile-time fact: the two wrappers
   really are the family profile at particular arguments, so an H2 facade for
   den Boer aliases the same program value the five-card facade already
   exposes. *)
Check (alias_same_type den_boer_profile.den_boer_profile
  (fun R : realType => fa_five_card_profile
     (den_boer_profile.den_boer_eps0_lt R) (den_boer_profile.den_boer_eps0_gt R)
     (den_boer_profile.den_boer_eps0_spectral R) 1)).
